### PR TITLE
Update inline docs + small fixes

### LINKED ISSUE #124: Better documentation in the code
Add more usage docs in the code so LLMs can extract and devs can stay in their IDE.

### PR DESCRIPTION
**Pull request by KyleAMathews**
Fix #124

### CODE REVIEW

File: packages/db-collections/src/electric.ts [hunk 1]
```diff
@@ -77,33 +77,179 @@ export interface ElectricCollectionConfig<
...
+   *   // Wait for the txid to be synced from server
+   *   await collection.utils.awaitTxId(result.txid)
+   *
+   *   return { txid: result.txid }
+   * }
    */
   onInsert?: (
     params: InsertMutationFnParams<ResolveType<TExplicit, TSchema, TFallback>>
-  ) => Promise<{ txid: string }>
+  ) => Promise<{ txid: string | Array<string> }>
```
Comment (KyleAMathews) [inline packages/db-collections/src/electric.ts:128]: I realized writing the docs that we should also support returning an array of txids e.g. if you do multiple api calls

File: packages/db/src/collection.ts [hunk 2]
```diff
@@ -1335,43 +1399,44 @@ export class CollectionImpl<
...
    * Updates one or more items in the collection using a callback function
-   * @param items - Single item/key or array of items/keys to update
+   * @param keys - Single key or array of keys to update
    * @param configOrCallback - Either update configuration or update callback
    * @param maybeCallback - Update callback if config was provided
    * @returns A Transaction object representing the update operation(s)
    * @throws {SchemaValidationError} If the updated data fails schema validation
    * @example
-   * // Update a single item
-   * update(todo, (draft) => { draft.completed = true })
```
Comment (KyleAMathews) [inline packages/db/src/collection.ts:1345]: these hadn't been updated 😅

File: packages/db/src/collection.ts [hunk 3]
```diff
@@ -1538,8 +1603,11 @@ export class CollectionImpl<
     // Create a new transaction with a mutation function that calls the onUpdate handler
     const directOpTransaction = createTransaction<T>({
       mutationFn: async (params) => {
-        // Call the onUpdate handler with the transaction
-        return this.config.onUpdate!(params)
+        // Call the onUpdate handler with the transaction and collection
+        return this.config.onUpdate!({
+          ...params,
+          collection: this as unknown as Collection<T, TKey, TUtils>,
```
Comment (KyleAMathews) [inline packages/db/src/collection.ts:1611]: it's handy to have direct access to the collection inside onInsert, etc. handlers

**Review by samwillis — APPROVED** [review]
Looks great :shipit:
