### PR TITLE
fix repeated renders when markReady called when collection already ready

### LINKED ISSUE #597: Prevent triggering `subscribeChanges` when long-polling request finishes with `up-to-date`
I noticed in our app that every time a long-polling request finishes, it causes all associated queries on that collection to return a new `data` object. In React, this triggers a lot of unnecessary re-renders.

This appears to be because the snapshot version is bumped whenever `subscribeChanges` is called, even if the list of changes is empty.

https://github.com/TanStack/db/blob/59b406edb57a087f440eace8fc6a75453d91796e/packages/react-db/src/useLiveQuery.ts#L390-L394

When I patch @tanstack/react-db as below, the problem goes away.

Image

### PR DESCRIPTION
**Pull request by samwillis**
This fixes #597

We were emitting an empty change event whenever `markReady` was called, which would happed after each Electric long polling request returned.

The code that triggers these additional empty events was added in #532 to fix a suck loading state. That PR introduced a test case that failed without this previous change. My change here initially caused a regression, but I went digging and found the *real* case of the stuck loading state and have fixed that 🥳

### CODE REVIEW

File: packages/db/src/collection/state.ts [hunk 1]
```diff
@@ -644,7 +644,7 @@ export class CollectionStateManager<
 
         // Ensure listeners are active before emitting this critical batch
         if (this.lifecycle.status !== `ready`) {
-          this.lifecycle.setStatus(`ready`)
+          this.lifecycle.markReady()
```
Comment (samwillis) [inline packages/db/src/collection/state.ts:647]: This change fixed what the *real* cause of the stuck loading status bug from #532. We should always use `markReady` when transitioning to ready.

File: packages/db/src/collection/lifecycle.ts [hunk 2]
```diff
@@ -90,7 +91,15 @@ export class CollectionLifecycleManager<
...
-  public setStatus(newStatus: CollectionStatus): void {
+  public setStatus(
+    newStatus: CollectionStatus,
+    allowReady: boolean = false
+  ): void {
+    if (newStatus === `ready` && !allowReady) {
+      throw new CollectionStateError(
+        `Cannot set status to anything other than ready, must use markReady instead`
+      )
+    }
```
Comment (samwillis) [inline packages/db/src/collection/lifecycle.ts:105]: I added this check to ensure we don't make the same mistake again when transitioning to ready - see other comment below.

File: packages/db/src/collection/lifecycle.ts [hunk 3]
```diff
@@ -146,12 +156,11 @@ export class CollectionLifecycleManager<
...
-
-    // Always notify dependents when markReady is called, after status is set
-    // This ensures live queries get notified when their dependencies become ready
-    if (this.changes.changeSubscriptions.size > 0) {
-      this.changes.emitEmptyReadyEvent()
+      // Notify dependents when markReady is called, after status is set
+      // This ensures live queries get notified when their dependencies become ready
+      if (this.changes.changeSubscriptions.size > 0) {
+        this.changes.emitEmptyReadyEvent()
+      }
```
Comment (samwillis) [inline packages/db/src/collection/lifecycle.ts:166]: Moving this inside the `if` above ensures we only send this empty change event when we first transition to ready. This is the fix to prevent additional renders.

File: packages/db/src/collection/state.ts (hunk 1 above)
Comment (KyleAMathews) [reply packages/db/src/collection/state.ts:647]: Maybe we just remove setStatus? It's nice to have proper functions where we can put in more logic when needed.

Comment (KyleAMathews) [reply packages/db/src/collection/state.ts:647]: not needed for this PR of course but a thought

File: packages/db/src/collection/lifecycle.ts [hunk 4]
```diff
@@ -90,7 +91,15 @@ export class CollectionLifecycleManager<
...
    * @private
    */
-  public setStatus(newStatus: CollectionStatus): void {
+  public setStatus(
+    newStatus: CollectionStatus,
+    allowReady: boolean = false
+  ): void {
+    if (newStatus === `ready` && !allowReady) {
+      throw new CollectionStateError(
+        `Cannot set status to anything other than ready, must use markReady instead`
```
Comment (KyleAMathews) [inline packages/db/src/collection/lifecycle.ts]:
```suggestion
        `You can't directly call "setStatus('ready'). You must use markReady instead.`
```

File: packages/db/src/collection/lifecycle.ts [hunk 5]
```diff
@@ -90,7 +91,15 @@ export class CollectionLifecycleManager<
    * Safely update the collection status with validation
    * @private
    */
-  public setStatus(newStatus: CollectionStatus): void {
+  public setStatus(
+    newStatus: CollectionStatus,
+    allowReady: boolean = false
+  ): void {
```
Comment (KyleAMathews) [inline packages/db/src/collection/lifecycle.ts:97]: We should prevent same status calls: `if (newStatus === this.status) return`

File: packages/db/src/collection/lifecycle.ts [hunk 6]
```diff
@@ -90,7 +91,15 @@ export class CollectionLifecycleManager<
...
+    if (newStatus === `ready` && !allowReady) {
```
Comment (KyleAMathews) [inline packages/db/src/collection/lifecycle.ts:98]: Add a comment (or add to the error) adding that `setStatus('ready')` is for internal use only.

File: .changeset/polite-eels-laugh.md [hunk 7]
```diff
@@ -0,0 +1,6 @@
+---
+"@tanstack/electric-db-collection": patch
+"@tanstack/db": patch
+---
+
+Fix repeated renders when markReady called when the collection was already ready. This would occur after each long poll on a Electric collection.
```
Comment (KyleAMathews) [inline .changeset/polite-eels-laugh.md]:
```suggestion
Fix repeated renders when markReady called when the collection was already ready. This would occur after each long poll on an Electric collection.
```

File: packages/db/src/collection/lifecycle.ts (hunk 5 above)
Comment (samwillis) [reply packages/db/src/collection/lifecycle.ts:97]: I'd like to change this in a followup PR as currently at least one test fails if we enforce that.

Comment (samwillis) [reply packages/db/src/collection/lifecycle.ts:97]: I would like to address this in a follow-up pr, when this is done it triggers at least one test failure.
