### PR TITLE
Fix returning an array of txids from an Electric collection handler

### LINKED ISSUE #793: Electric collection mutations fail to wait for array of txids
- [x] I've validated the bug against the latest version of DB packages

**Describe the bug**
I'm experiencing an issue with awaiting multiple txids in an electric collection mutation handler. I'm getting a `TimeoutWaitingForTxIdError` as soon as one of the txids are seen on the stream, even though I'm well below the timeout.

**To Reproduce**

Define a collection like this:
```ts
const todosCollection = createCollection(
  electricCollectionOptions({
    id: 'todos',
    getKey: (item) => item.id,
    shapeOptions: {
      url: '/api/todos',
      params: { table: 'todos' },
    },
    onInsert: async ({ transaction }) => {
      const txids = await Promise.all(
        transaction.mutations.map((mutation) =>
          api.todos.create(mutation.modified),
        )
      );

      return { txid: txids };
    }
  })
)
```

Run a mutation (single or multiple entries):
```ts
// ❌ Throws TimeoutWaitingForTxIdError before 5 second timeout
todosCollection.insert({ id: crypto.randomUUID(), title: 'New todo' })

// ❌ Throws TimeoutWaitingForTxIdError before 5 second timeout
todosCollection.insert([{ id: crypto.randomUUID(), title: 'New todo 1' }, { id: crypto.randomUUID(), title: 'New todo 2' }])
```

**Expected behavior**
I expect the mutations not to throw `TimeoutWaitingForTxIdError` unless the transaction takes > 5 seconds to appear on stream.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 141.0.7390.123

**Additional context**
The waiting works fine when returning a single txid instead of a txid array in mutation handler.

This modification to [processMatchingStrategy](https://github.com/TanStack/db/blob/main/packages/electric-db-collection/src/electric.ts#L502) fixes the issue:
```
await Promise.all(result.txid.map((txid) => awaitTxId(txid)))
```

### PR DESCRIPTION
**Pull request by KyleAMathews**
Fixes #793

### CODE REVIEW

File: packages/electric-db-collection/src/electric.ts [hunk 1]
```diff
@@ -506,7 +506,8 @@ export function electricCollectionOptions(
     if (result && `txid` in result) {
       // Handle both single txid and array of txids
       if (Array.isArray(result.txid)) {
-        await Promise.all(result.txid.map(awaitTxId))
+        // Use arrow function to avoid passing map's index as timeout parameter
```
Comment (samwillis) [inline packages/electric-db-collection/src/electric.ts]: llm comment
