### PR TITLE
fix join expression order bug and add validation

### LINKED ISSUE #277: Add support for SQL-style self-joins on the same table
Self-joins currently crash the process.

**Minimal reproduction:**
```ts
useLiveQuery(
  q => q.from({ users })
    .join(
      { parentUsers: users },
      ({ users, parentUsers }) => eq(users.parentId, parentUsers.id),
      'inner',
    )
)
```

**Expected:**
returns joined rows.

**Actual:**
memory exhaustion / crash (tab becomes unresponsive without showing error messages in the console and with memory usage climbing).

### PR DESCRIPTION
**Pull request by samwillis**
fixes #277

Currently the order of the references in the join `eq(left.prop, right.prop)` was required but not validated. This changes it to work either way (you can specify them in reverse) and validates and rejects other mistakes.

### CODE REVIEW

**Review by KyleAMathews — APPROVED** [review]
Oh nice! I didn't like having to remember which order to put things in haha.

File: packages/db/src/query/compiler/joins.ts [hunk 1]
```diff
@@ -121,6 +134,83 @@ function processJoin(
...
+      for (const arg of expr.args) {
+        const alias = getTableAliasFromExpression(arg)
+        if (alias) {
+          tableAliases.add(alias)
+        }
+      }
+      // If all arguments refer to the same table, return that table alias
+      return tableAliases.size === 1 ? Array.from(tableAliases)[0]! : null
+    }
+    case `val`:
```
Comment (kevin-dp) [inline packages/db/src/query/compiler/joins.ts]: Could remove this case in favor of the default case.

File: packages/db/src/query/compiler/joins.ts [hunk 2]
```diff
@@ -121,6 +134,83 @@ function processJoin(
...
+
+  // If left expression refers to joined table and right refers to main table, swap them
+  if (
+    leftTableAlias === joinedTableAlias &&
+    rightTableAlias === mainTableAlias
+  ) {
+    return { mainExpr: right, joinedExpr: left }
+  }
+
+  // If both expressions refer to the same table, this is an invalid join
```
Comment (kevin-dp) [inline packages/db/src/query/compiler/joins.ts]: This comment got me wondering if it was not possible to self-join. But in the tests i see that it is possible but the aliases need to be different. Perhaps we can improve this comment by saying:
> if both expressions refer to the same **alias**, this is an invalid join

**Review by kevin-dp — APPROVED** [review]
